# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from rustycluster.proto import rustycluster_pb2 as rustycluster__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rustycluster_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KeyValueServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Authenticate = channel.unary_unary(
                '/rustycluster.KeyValueService/Authenticate',
                request_serializer=rustycluster__pb2.AuthenticateRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.AuthenticateResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/rustycluster.KeyValueService/Ping',
                request_serializer=rustycluster__pb2.PingRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.PingResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/rustycluster.KeyValueService/HealthCheck',
                request_serializer=rustycluster__pb2.PingRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.PingResponse.FromString,
                _registered_method=True)
        self.Set = channel.unary_unary(
                '/rustycluster.KeyValueService/Set',
                request_serializer=rustycluster__pb2.SetRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.SetResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/rustycluster.KeyValueService/Get',
                request_serializer=rustycluster__pb2.GetRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.GetResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/rustycluster.KeyValueService/Delete',
                request_serializer=rustycluster__pb2.DeleteRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.SetEx = channel.unary_unary(
                '/rustycluster.KeyValueService/SetEx',
                request_serializer=rustycluster__pb2.SetExRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.SetExResponse.FromString,
                _registered_method=True)
        self.SetExpiry = channel.unary_unary(
                '/rustycluster.KeyValueService/SetExpiry',
                request_serializer=rustycluster__pb2.SetExpiryRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.SetExpiryResponse.FromString,
                _registered_method=True)
        self.IncrBy = channel.unary_unary(
                '/rustycluster.KeyValueService/IncrBy',
                request_serializer=rustycluster__pb2.IncrByRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.IncrByResponse.FromString,
                _registered_method=True)
        self.DecrBy = channel.unary_unary(
                '/rustycluster.KeyValueService/DecrBy',
                request_serializer=rustycluster__pb2.DecrByRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.DecrByResponse.FromString,
                _registered_method=True)
        self.IncrByFloat = channel.unary_unary(
                '/rustycluster.KeyValueService/IncrByFloat',
                request_serializer=rustycluster__pb2.IncrByFloatRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.IncrByFloatResponse.FromString,
                _registered_method=True)
        self.HSet = channel.unary_unary(
                '/rustycluster.KeyValueService/HSet',
                request_serializer=rustycluster__pb2.HSetRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.HSetResponse.FromString,
                _registered_method=True)
        self.HGet = channel.unary_unary(
                '/rustycluster.KeyValueService/HGet',
                request_serializer=rustycluster__pb2.HGetRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.HGetResponse.FromString,
                _registered_method=True)
        self.HGetAll = channel.unary_unary(
                '/rustycluster.KeyValueService/HGetAll',
                request_serializer=rustycluster__pb2.HGetAllRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.HGetAllResponse.FromString,
                _registered_method=True)
        self.HIncrBy = channel.unary_unary(
                '/rustycluster.KeyValueService/HIncrBy',
                request_serializer=rustycluster__pb2.HIncrByRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.HIncrByResponse.FromString,
                _registered_method=True)
        self.HDecrBy = channel.unary_unary(
                '/rustycluster.KeyValueService/HDecrBy',
                request_serializer=rustycluster__pb2.HDecrByRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.HDecrByResponse.FromString,
                _registered_method=True)
        self.HIncrByFloat = channel.unary_unary(
                '/rustycluster.KeyValueService/HIncrByFloat',
                request_serializer=rustycluster__pb2.HIncrByFloatRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.HIncrByFloatResponse.FromString,
                _registered_method=True)
        self.HMSet = channel.unary_unary(
                '/rustycluster.KeyValueService/HMSet',
                request_serializer=rustycluster__pb2.HMSetRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.HMSetResponse.FromString,
                _registered_method=True)
        self.HExists = channel.unary_unary(
                '/rustycluster.KeyValueService/HExists',
                request_serializer=rustycluster__pb2.HExistsRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.HExistsResponse.FromString,
                _registered_method=True)
        self.HDel = channel.unary_unary(
                '/rustycluster.KeyValueService/HDel',
                request_serializer=rustycluster__pb2.HDelRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.HDelResponse.FromString,
                _registered_method=True)
        self.HScan = channel.unary_unary(
                '/rustycluster.KeyValueService/HScan',
                request_serializer=rustycluster__pb2.HScanRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.HScanResponse.FromString,
                _registered_method=True)
        self.HLen = channel.unary_unary(
                '/rustycluster.KeyValueService/HLen',
                request_serializer=rustycluster__pb2.HLenRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.HLenResponse.FromString,
                _registered_method=True)
        self.HSetNX = channel.unary_unary(
                '/rustycluster.KeyValueService/HSetNX',
                request_serializer=rustycluster__pb2.HSetNXRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.HSetNXResponse.FromString,
                _registered_method=True)
        self.HExpire = channel.unary_unary(
                '/rustycluster.KeyValueService/HExpire',
                request_serializer=rustycluster__pb2.HExpireRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.HExpireResponse.FromString,
                _registered_method=True)
        self.HSetBytes = channel.unary_unary(
                '/rustycluster.KeyValueService/HSetBytes',
                request_serializer=rustycluster__pb2.HSetBytesRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.HSetBytesResponse.FromString,
                _registered_method=True)
        self.HGetBytes = channel.unary_unary(
                '/rustycluster.KeyValueService/HGetBytes',
                request_serializer=rustycluster__pb2.HGetBytesRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.HGetBytesResponse.FromString,
                _registered_method=True)
        self.HScanBytes = channel.unary_unary(
                '/rustycluster.KeyValueService/HScanBytes',
                request_serializer=rustycluster__pb2.HScanBytesRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.HScanBytesResponse.FromString,
                _registered_method=True)
        self.HGetAllBytes = channel.unary_unary(
                '/rustycluster.KeyValueService/HGetAllBytes',
                request_serializer=rustycluster__pb2.HGetAllBytesRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.HGetAllBytesResponse.FromString,
                _registered_method=True)
        self.SAdd = channel.unary_unary(
                '/rustycluster.KeyValueService/SAdd',
                request_serializer=rustycluster__pb2.SAddRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.SAddResponse.FromString,
                _registered_method=True)
        self.SMembers = channel.unary_unary(
                '/rustycluster.KeyValueService/SMembers',
                request_serializer=rustycluster__pb2.SMembersRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.SMembersResponse.FromString,
                _registered_method=True)
        self.SRem = channel.unary_unary(
                '/rustycluster.KeyValueService/SRem',
                request_serializer=rustycluster__pb2.SRemRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.SRemResponse.FromString,
                _registered_method=True)
        self.SCard = channel.unary_unary(
                '/rustycluster.KeyValueService/SCard',
                request_serializer=rustycluster__pb2.SCardRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.SCardResponse.FromString,
                _registered_method=True)
        self.SScan = channel.unary_unary(
                '/rustycluster.KeyValueService/SScan',
                request_serializer=rustycluster__pb2.SScanRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.SScanResponse.FromString,
                _registered_method=True)
        self.SetNX = channel.unary_unary(
                '/rustycluster.KeyValueService/SetNX',
                request_serializer=rustycluster__pb2.SetNXRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.SetNXResponse.FromString,
                _registered_method=True)
        self.Exists = channel.unary_unary(
                '/rustycluster.KeyValueService/Exists',
                request_serializer=rustycluster__pb2.ExistsRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.ExistsResponse.FromString,
                _registered_method=True)
        self.DelMultiple = channel.unary_unary(
                '/rustycluster.KeyValueService/DelMultiple',
                request_serializer=rustycluster__pb2.DelMultipleRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.DelMultipleResponse.FromString,
                _registered_method=True)
        self.Keys = channel.unary_unary(
                '/rustycluster.KeyValueService/Keys',
                request_serializer=rustycluster__pb2.KeysRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.KeysResponse.FromString,
                _registered_method=True)
        self.MGet = channel.unary_unary(
                '/rustycluster.KeyValueService/MGet',
                request_serializer=rustycluster__pb2.MGetRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.MGetResponse.FromString,
                _registered_method=True)
        self.LoadScript = channel.unary_unary(
                '/rustycluster.KeyValueService/LoadScript',
                request_serializer=rustycluster__pb2.LoadScriptRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.LoadScriptResponse.FromString,
                _registered_method=True)
        self.EvalSha = channel.unary_unary(
                '/rustycluster.KeyValueService/EvalSha',
                request_serializer=rustycluster__pb2.EvalShaRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.EvalShaResponse.FromString,
                _registered_method=True)
        self.LPush = channel.unary_unary(
                '/rustycluster.KeyValueService/LPush',
                request_serializer=rustycluster__pb2.LPushRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.LPushResponse.FromString,
                _registered_method=True)
        self.RPush = channel.unary_unary(
                '/rustycluster.KeyValueService/RPush',
                request_serializer=rustycluster__pb2.RPushRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.RPushResponse.FromString,
                _registered_method=True)
        self.LPop = channel.unary_unary(
                '/rustycluster.KeyValueService/LPop',
                request_serializer=rustycluster__pb2.LPopRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.LPopResponse.FromString,
                _registered_method=True)
        self.RPop = channel.unary_unary(
                '/rustycluster.KeyValueService/RPop',
                request_serializer=rustycluster__pb2.RPopRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.RPopResponse.FromString,
                _registered_method=True)
        self.LRange = channel.unary_unary(
                '/rustycluster.KeyValueService/LRange',
                request_serializer=rustycluster__pb2.LRangeRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.LRangeResponse.FromString,
                _registered_method=True)
        self.LLen = channel.unary_unary(
                '/rustycluster.KeyValueService/LLen',
                request_serializer=rustycluster__pb2.LLenRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.LLenResponse.FromString,
                _registered_method=True)
        self.LTrim = channel.unary_unary(
                '/rustycluster.KeyValueService/LTrim',
                request_serializer=rustycluster__pb2.LTrimRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.LTrimResponse.FromString,
                _registered_method=True)
        self.LIndex = channel.unary_unary(
                '/rustycluster.KeyValueService/LIndex',
                request_serializer=rustycluster__pb2.LIndexRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.LIndexResponse.FromString,
                _registered_method=True)
        self.LSet = channel.unary_unary(
                '/rustycluster.KeyValueService/LSet',
                request_serializer=rustycluster__pb2.LSetRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.LSetResponse.FromString,
                _registered_method=True)
        self.LRem = channel.unary_unary(
                '/rustycluster.KeyValueService/LRem',
                request_serializer=rustycluster__pb2.LRemRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.LRemResponse.FromString,
                _registered_method=True)
        self.LInsert = channel.unary_unary(
                '/rustycluster.KeyValueService/LInsert',
                request_serializer=rustycluster__pb2.LInsertRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.LInsertResponse.FromString,
                _registered_method=True)
        self.LPushX = channel.unary_unary(
                '/rustycluster.KeyValueService/LPushX',
                request_serializer=rustycluster__pb2.LPushXRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.LPushXResponse.FromString,
                _registered_method=True)
        self.RPushX = channel.unary_unary(
                '/rustycluster.KeyValueService/RPushX',
                request_serializer=rustycluster__pb2.RPushXRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.RPushXResponse.FromString,
                _registered_method=True)
        self.LPos = channel.unary_unary(
                '/rustycluster.KeyValueService/LPos',
                request_serializer=rustycluster__pb2.LPosRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.LPosResponse.FromString,
                _registered_method=True)
        self.XAdd = channel.unary_unary(
                '/rustycluster.KeyValueService/XAdd',
                request_serializer=rustycluster__pb2.XAddRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.XAddResponse.FromString,
                _registered_method=True)
        self.XRead = channel.unary_unary(
                '/rustycluster.KeyValueService/XRead',
                request_serializer=rustycluster__pb2.XReadRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.XReadResponse.FromString,
                _registered_method=True)
        self.BatchWrite = channel.unary_unary(
                '/rustycluster.KeyValueService/BatchWrite',
                request_serializer=rustycluster__pb2.BatchWriteRequest.SerializeToString,
                response_deserializer=rustycluster__pb2.BatchWriteResponse.FromString,
                _registered_method=True)


class KeyValueServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Authenticate(self, request, context):
        """Authentication operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """System operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Set(self, request, context):
        """String operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetEx(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetExpiry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IncrBy(self, request, context):
        """Numeric operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DecrBy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IncrByFloat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HSet(self, request, context):
        """Hash operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HGet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HGetAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HIncrBy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HDecrBy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HIncrByFloat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HMSet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HExists(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HDel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HScan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HLen(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HSetNX(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HExpire(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HSetBytes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HGetBytes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HScanBytes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HGetAllBytes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SAdd(self, request, context):
        """Set operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SMembers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SRem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SCard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SScan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetNX(self, request, context):
        """Key operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Exists(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DelMultiple(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Keys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MGet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadScript(self, request, context):
        """Script operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvalSha(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LPush(self, request, context):
        """List (queue) operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RPush(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LPop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RPop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LLen(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LTrim(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LSet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LRem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LInsert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LPushX(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RPushX(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LPos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def XAdd(self, request, context):
        """Stream operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def XRead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchWrite(self, request, context):
        """Batch operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KeyValueServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Authenticate': grpc.unary_unary_rpc_method_handler(
                    servicer.Authenticate,
                    request_deserializer=rustycluster__pb2.AuthenticateRequest.FromString,
                    response_serializer=rustycluster__pb2.AuthenticateResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=rustycluster__pb2.PingRequest.FromString,
                    response_serializer=rustycluster__pb2.PingResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=rustycluster__pb2.PingRequest.FromString,
                    response_serializer=rustycluster__pb2.PingResponse.SerializeToString,
            ),
            'Set': grpc.unary_unary_rpc_method_handler(
                    servicer.Set,
                    request_deserializer=rustycluster__pb2.SetRequest.FromString,
                    response_serializer=rustycluster__pb2.SetResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=rustycluster__pb2.GetRequest.FromString,
                    response_serializer=rustycluster__pb2.GetResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=rustycluster__pb2.DeleteRequest.FromString,
                    response_serializer=rustycluster__pb2.DeleteResponse.SerializeToString,
            ),
            'SetEx': grpc.unary_unary_rpc_method_handler(
                    servicer.SetEx,
                    request_deserializer=rustycluster__pb2.SetExRequest.FromString,
                    response_serializer=rustycluster__pb2.SetExResponse.SerializeToString,
            ),
            'SetExpiry': grpc.unary_unary_rpc_method_handler(
                    servicer.SetExpiry,
                    request_deserializer=rustycluster__pb2.SetExpiryRequest.FromString,
                    response_serializer=rustycluster__pb2.SetExpiryResponse.SerializeToString,
            ),
            'IncrBy': grpc.unary_unary_rpc_method_handler(
                    servicer.IncrBy,
                    request_deserializer=rustycluster__pb2.IncrByRequest.FromString,
                    response_serializer=rustycluster__pb2.IncrByResponse.SerializeToString,
            ),
            'DecrBy': grpc.unary_unary_rpc_method_handler(
                    servicer.DecrBy,
                    request_deserializer=rustycluster__pb2.DecrByRequest.FromString,
                    response_serializer=rustycluster__pb2.DecrByResponse.SerializeToString,
            ),
            'IncrByFloat': grpc.unary_unary_rpc_method_handler(
                    servicer.IncrByFloat,
                    request_deserializer=rustycluster__pb2.IncrByFloatRequest.FromString,
                    response_serializer=rustycluster__pb2.IncrByFloatResponse.SerializeToString,
            ),
            'HSet': grpc.unary_unary_rpc_method_handler(
                    servicer.HSet,
                    request_deserializer=rustycluster__pb2.HSetRequest.FromString,
                    response_serializer=rustycluster__pb2.HSetResponse.SerializeToString,
            ),
            'HGet': grpc.unary_unary_rpc_method_handler(
                    servicer.HGet,
                    request_deserializer=rustycluster__pb2.HGetRequest.FromString,
                    response_serializer=rustycluster__pb2.HGetResponse.SerializeToString,
            ),
            'HGetAll': grpc.unary_unary_rpc_method_handler(
                    servicer.HGetAll,
                    request_deserializer=rustycluster__pb2.HGetAllRequest.FromString,
                    response_serializer=rustycluster__pb2.HGetAllResponse.SerializeToString,
            ),
            'HIncrBy': grpc.unary_unary_rpc_method_handler(
                    servicer.HIncrBy,
                    request_deserializer=rustycluster__pb2.HIncrByRequest.FromString,
                    response_serializer=rustycluster__pb2.HIncrByResponse.SerializeToString,
            ),
            'HDecrBy': grpc.unary_unary_rpc_method_handler(
                    servicer.HDecrBy,
                    request_deserializer=rustycluster__pb2.HDecrByRequest.FromString,
                    response_serializer=rustycluster__pb2.HDecrByResponse.SerializeToString,
            ),
            'HIncrByFloat': grpc.unary_unary_rpc_method_handler(
                    servicer.HIncrByFloat,
                    request_deserializer=rustycluster__pb2.HIncrByFloatRequest.FromString,
                    response_serializer=rustycluster__pb2.HIncrByFloatResponse.SerializeToString,
            ),
            'HMSet': grpc.unary_unary_rpc_method_handler(
                    servicer.HMSet,
                    request_deserializer=rustycluster__pb2.HMSetRequest.FromString,
                    response_serializer=rustycluster__pb2.HMSetResponse.SerializeToString,
            ),
            'HExists': grpc.unary_unary_rpc_method_handler(
                    servicer.HExists,
                    request_deserializer=rustycluster__pb2.HExistsRequest.FromString,
                    response_serializer=rustycluster__pb2.HExistsResponse.SerializeToString,
            ),
            'HDel': grpc.unary_unary_rpc_method_handler(
                    servicer.HDel,
                    request_deserializer=rustycluster__pb2.HDelRequest.FromString,
                    response_serializer=rustycluster__pb2.HDelResponse.SerializeToString,
            ),
            'HScan': grpc.unary_unary_rpc_method_handler(
                    servicer.HScan,
                    request_deserializer=rustycluster__pb2.HScanRequest.FromString,
                    response_serializer=rustycluster__pb2.HScanResponse.SerializeToString,
            ),
            'HLen': grpc.unary_unary_rpc_method_handler(
                    servicer.HLen,
                    request_deserializer=rustycluster__pb2.HLenRequest.FromString,
                    response_serializer=rustycluster__pb2.HLenResponse.SerializeToString,
            ),
            'HSetNX': grpc.unary_unary_rpc_method_handler(
                    servicer.HSetNX,
                    request_deserializer=rustycluster__pb2.HSetNXRequest.FromString,
                    response_serializer=rustycluster__pb2.HSetNXResponse.SerializeToString,
            ),
            'HExpire': grpc.unary_unary_rpc_method_handler(
                    servicer.HExpire,
                    request_deserializer=rustycluster__pb2.HExpireRequest.FromString,
                    response_serializer=rustycluster__pb2.HExpireResponse.SerializeToString,
            ),
            'HSetBytes': grpc.unary_unary_rpc_method_handler(
                    servicer.HSetBytes,
                    request_deserializer=rustycluster__pb2.HSetBytesRequest.FromString,
                    response_serializer=rustycluster__pb2.HSetBytesResponse.SerializeToString,
            ),
            'HGetBytes': grpc.unary_unary_rpc_method_handler(
                    servicer.HGetBytes,
                    request_deserializer=rustycluster__pb2.HGetBytesRequest.FromString,
                    response_serializer=rustycluster__pb2.HGetBytesResponse.SerializeToString,
            ),
            'HScanBytes': grpc.unary_unary_rpc_method_handler(
                    servicer.HScanBytes,
                    request_deserializer=rustycluster__pb2.HScanBytesRequest.FromString,
                    response_serializer=rustycluster__pb2.HScanBytesResponse.SerializeToString,
            ),
            'HGetAllBytes': grpc.unary_unary_rpc_method_handler(
                    servicer.HGetAllBytes,
                    request_deserializer=rustycluster__pb2.HGetAllBytesRequest.FromString,
                    response_serializer=rustycluster__pb2.HGetAllBytesResponse.SerializeToString,
            ),
            'SAdd': grpc.unary_unary_rpc_method_handler(
                    servicer.SAdd,
                    request_deserializer=rustycluster__pb2.SAddRequest.FromString,
                    response_serializer=rustycluster__pb2.SAddResponse.SerializeToString,
            ),
            'SMembers': grpc.unary_unary_rpc_method_handler(
                    servicer.SMembers,
                    request_deserializer=rustycluster__pb2.SMembersRequest.FromString,
                    response_serializer=rustycluster__pb2.SMembersResponse.SerializeToString,
            ),
            'SRem': grpc.unary_unary_rpc_method_handler(
                    servicer.SRem,
                    request_deserializer=rustycluster__pb2.SRemRequest.FromString,
                    response_serializer=rustycluster__pb2.SRemResponse.SerializeToString,
            ),
            'SCard': grpc.unary_unary_rpc_method_handler(
                    servicer.SCard,
                    request_deserializer=rustycluster__pb2.SCardRequest.FromString,
                    response_serializer=rustycluster__pb2.SCardResponse.SerializeToString,
            ),
            'SScan': grpc.unary_unary_rpc_method_handler(
                    servicer.SScan,
                    request_deserializer=rustycluster__pb2.SScanRequest.FromString,
                    response_serializer=rustycluster__pb2.SScanResponse.SerializeToString,
            ),
            'SetNX': grpc.unary_unary_rpc_method_handler(
                    servicer.SetNX,
                    request_deserializer=rustycluster__pb2.SetNXRequest.FromString,
                    response_serializer=rustycluster__pb2.SetNXResponse.SerializeToString,
            ),
            'Exists': grpc.unary_unary_rpc_method_handler(
                    servicer.Exists,
                    request_deserializer=rustycluster__pb2.ExistsRequest.FromString,
                    response_serializer=rustycluster__pb2.ExistsResponse.SerializeToString,
            ),
            'DelMultiple': grpc.unary_unary_rpc_method_handler(
                    servicer.DelMultiple,
                    request_deserializer=rustycluster__pb2.DelMultipleRequest.FromString,
                    response_serializer=rustycluster__pb2.DelMultipleResponse.SerializeToString,
            ),
            'Keys': grpc.unary_unary_rpc_method_handler(
                    servicer.Keys,
                    request_deserializer=rustycluster__pb2.KeysRequest.FromString,
                    response_serializer=rustycluster__pb2.KeysResponse.SerializeToString,
            ),
            'MGet': grpc.unary_unary_rpc_method_handler(
                    servicer.MGet,
                    request_deserializer=rustycluster__pb2.MGetRequest.FromString,
                    response_serializer=rustycluster__pb2.MGetResponse.SerializeToString,
            ),
            'LoadScript': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadScript,
                    request_deserializer=rustycluster__pb2.LoadScriptRequest.FromString,
                    response_serializer=rustycluster__pb2.LoadScriptResponse.SerializeToString,
            ),
            'EvalSha': grpc.unary_unary_rpc_method_handler(
                    servicer.EvalSha,
                    request_deserializer=rustycluster__pb2.EvalShaRequest.FromString,
                    response_serializer=rustycluster__pb2.EvalShaResponse.SerializeToString,
            ),
            'LPush': grpc.unary_unary_rpc_method_handler(
                    servicer.LPush,
                    request_deserializer=rustycluster__pb2.LPushRequest.FromString,
                    response_serializer=rustycluster__pb2.LPushResponse.SerializeToString,
            ),
            'RPush': grpc.unary_unary_rpc_method_handler(
                    servicer.RPush,
                    request_deserializer=rustycluster__pb2.RPushRequest.FromString,
                    response_serializer=rustycluster__pb2.RPushResponse.SerializeToString,
            ),
            'LPop': grpc.unary_unary_rpc_method_handler(
                    servicer.LPop,
                    request_deserializer=rustycluster__pb2.LPopRequest.FromString,
                    response_serializer=rustycluster__pb2.LPopResponse.SerializeToString,
            ),
            'RPop': grpc.unary_unary_rpc_method_handler(
                    servicer.RPop,
                    request_deserializer=rustycluster__pb2.RPopRequest.FromString,
                    response_serializer=rustycluster__pb2.RPopResponse.SerializeToString,
            ),
            'LRange': grpc.unary_unary_rpc_method_handler(
                    servicer.LRange,
                    request_deserializer=rustycluster__pb2.LRangeRequest.FromString,
                    response_serializer=rustycluster__pb2.LRangeResponse.SerializeToString,
            ),
            'LLen': grpc.unary_unary_rpc_method_handler(
                    servicer.LLen,
                    request_deserializer=rustycluster__pb2.LLenRequest.FromString,
                    response_serializer=rustycluster__pb2.LLenResponse.SerializeToString,
            ),
            'LTrim': grpc.unary_unary_rpc_method_handler(
                    servicer.LTrim,
                    request_deserializer=rustycluster__pb2.LTrimRequest.FromString,
                    response_serializer=rustycluster__pb2.LTrimResponse.SerializeToString,
            ),
            'LIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.LIndex,
                    request_deserializer=rustycluster__pb2.LIndexRequest.FromString,
                    response_serializer=rustycluster__pb2.LIndexResponse.SerializeToString,
            ),
            'LSet': grpc.unary_unary_rpc_method_handler(
                    servicer.LSet,
                    request_deserializer=rustycluster__pb2.LSetRequest.FromString,
                    response_serializer=rustycluster__pb2.LSetResponse.SerializeToString,
            ),
            'LRem': grpc.unary_unary_rpc_method_handler(
                    servicer.LRem,
                    request_deserializer=rustycluster__pb2.LRemRequest.FromString,
                    response_serializer=rustycluster__pb2.LRemResponse.SerializeToString,
            ),
            'LInsert': grpc.unary_unary_rpc_method_handler(
                    servicer.LInsert,
                    request_deserializer=rustycluster__pb2.LInsertRequest.FromString,
                    response_serializer=rustycluster__pb2.LInsertResponse.SerializeToString,
            ),
            'LPushX': grpc.unary_unary_rpc_method_handler(
                    servicer.LPushX,
                    request_deserializer=rustycluster__pb2.LPushXRequest.FromString,
                    response_serializer=rustycluster__pb2.LPushXResponse.SerializeToString,
            ),
            'RPushX': grpc.unary_unary_rpc_method_handler(
                    servicer.RPushX,
                    request_deserializer=rustycluster__pb2.RPushXRequest.FromString,
                    response_serializer=rustycluster__pb2.RPushXResponse.SerializeToString,
            ),
            'LPos': grpc.unary_unary_rpc_method_handler(
                    servicer.LPos,
                    request_deserializer=rustycluster__pb2.LPosRequest.FromString,
                    response_serializer=rustycluster__pb2.LPosResponse.SerializeToString,
            ),
            'XAdd': grpc.unary_unary_rpc_method_handler(
                    servicer.XAdd,
                    request_deserializer=rustycluster__pb2.XAddRequest.FromString,
                    response_serializer=rustycluster__pb2.XAddResponse.SerializeToString,
            ),
            'XRead': grpc.unary_unary_rpc_method_handler(
                    servicer.XRead,
                    request_deserializer=rustycluster__pb2.XReadRequest.FromString,
                    response_serializer=rustycluster__pb2.XReadResponse.SerializeToString,
            ),
            'BatchWrite': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchWrite,
                    request_deserializer=rustycluster__pb2.BatchWriteRequest.FromString,
                    response_serializer=rustycluster__pb2.BatchWriteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rustycluster.KeyValueService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rustycluster.KeyValueService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KeyValueService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Authenticate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/Authenticate',
            rustycluster__pb2.AuthenticateRequest.SerializeToString,
            rustycluster__pb2.AuthenticateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/Ping',
            rustycluster__pb2.PingRequest.SerializeToString,
            rustycluster__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/HealthCheck',
            rustycluster__pb2.PingRequest.SerializeToString,
            rustycluster__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Set(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/Set',
            rustycluster__pb2.SetRequest.SerializeToString,
            rustycluster__pb2.SetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/Get',
            rustycluster__pb2.GetRequest.SerializeToString,
            rustycluster__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/Delete',
            rustycluster__pb2.DeleteRequest.SerializeToString,
            rustycluster__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetEx(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/SetEx',
            rustycluster__pb2.SetExRequest.SerializeToString,
            rustycluster__pb2.SetExResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetExpiry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/SetExpiry',
            rustycluster__pb2.SetExpiryRequest.SerializeToString,
            rustycluster__pb2.SetExpiryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IncrBy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/IncrBy',
            rustycluster__pb2.IncrByRequest.SerializeToString,
            rustycluster__pb2.IncrByResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DecrBy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/DecrBy',
            rustycluster__pb2.DecrByRequest.SerializeToString,
            rustycluster__pb2.DecrByResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IncrByFloat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/IncrByFloat',
            rustycluster__pb2.IncrByFloatRequest.SerializeToString,
            rustycluster__pb2.IncrByFloatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/HSet',
            rustycluster__pb2.HSetRequest.SerializeToString,
            rustycluster__pb2.HSetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HGet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/HGet',
            rustycluster__pb2.HGetRequest.SerializeToString,
            rustycluster__pb2.HGetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HGetAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/HGetAll',
            rustycluster__pb2.HGetAllRequest.SerializeToString,
            rustycluster__pb2.HGetAllResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HIncrBy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/HIncrBy',
            rustycluster__pb2.HIncrByRequest.SerializeToString,
            rustycluster__pb2.HIncrByResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HDecrBy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/HDecrBy',
            rustycluster__pb2.HDecrByRequest.SerializeToString,
            rustycluster__pb2.HDecrByResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HIncrByFloat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/HIncrByFloat',
            rustycluster__pb2.HIncrByFloatRequest.SerializeToString,
            rustycluster__pb2.HIncrByFloatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HMSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/HMSet',
            rustycluster__pb2.HMSetRequest.SerializeToString,
            rustycluster__pb2.HMSetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HExists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/HExists',
            rustycluster__pb2.HExistsRequest.SerializeToString,
            rustycluster__pb2.HExistsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HDel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/HDel',
            rustycluster__pb2.HDelRequest.SerializeToString,
            rustycluster__pb2.HDelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HScan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/HScan',
            rustycluster__pb2.HScanRequest.SerializeToString,
            rustycluster__pb2.HScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HLen(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/HLen',
            rustycluster__pb2.HLenRequest.SerializeToString,
            rustycluster__pb2.HLenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HSetNX(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/HSetNX',
            rustycluster__pb2.HSetNXRequest.SerializeToString,
            rustycluster__pb2.HSetNXResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HExpire(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/HExpire',
            rustycluster__pb2.HExpireRequest.SerializeToString,
            rustycluster__pb2.HExpireResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HSetBytes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/HSetBytes',
            rustycluster__pb2.HSetBytesRequest.SerializeToString,
            rustycluster__pb2.HSetBytesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HGetBytes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/HGetBytes',
            rustycluster__pb2.HGetBytesRequest.SerializeToString,
            rustycluster__pb2.HGetBytesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HScanBytes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/HScanBytes',
            rustycluster__pb2.HScanBytesRequest.SerializeToString,
            rustycluster__pb2.HScanBytesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HGetAllBytes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/HGetAllBytes',
            rustycluster__pb2.HGetAllBytesRequest.SerializeToString,
            rustycluster__pb2.HGetAllBytesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SAdd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/SAdd',
            rustycluster__pb2.SAddRequest.SerializeToString,
            rustycluster__pb2.SAddResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SMembers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/SMembers',
            rustycluster__pb2.SMembersRequest.SerializeToString,
            rustycluster__pb2.SMembersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SRem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/SRem',
            rustycluster__pb2.SRemRequest.SerializeToString,
            rustycluster__pb2.SRemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/SCard',
            rustycluster__pb2.SCardRequest.SerializeToString,
            rustycluster__pb2.SCardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SScan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/SScan',
            rustycluster__pb2.SScanRequest.SerializeToString,
            rustycluster__pb2.SScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetNX(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/SetNX',
            rustycluster__pb2.SetNXRequest.SerializeToString,
            rustycluster__pb2.SetNXResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Exists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/Exists',
            rustycluster__pb2.ExistsRequest.SerializeToString,
            rustycluster__pb2.ExistsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DelMultiple(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/DelMultiple',
            rustycluster__pb2.DelMultipleRequest.SerializeToString,
            rustycluster__pb2.DelMultipleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Keys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/Keys',
            rustycluster__pb2.KeysRequest.SerializeToString,
            rustycluster__pb2.KeysResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MGet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/MGet',
            rustycluster__pb2.MGetRequest.SerializeToString,
            rustycluster__pb2.MGetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadScript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/LoadScript',
            rustycluster__pb2.LoadScriptRequest.SerializeToString,
            rustycluster__pb2.LoadScriptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvalSha(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/EvalSha',
            rustycluster__pb2.EvalShaRequest.SerializeToString,
            rustycluster__pb2.EvalShaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LPush(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/LPush',
            rustycluster__pb2.LPushRequest.SerializeToString,
            rustycluster__pb2.LPushResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RPush(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/RPush',
            rustycluster__pb2.RPushRequest.SerializeToString,
            rustycluster__pb2.RPushResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LPop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/LPop',
            rustycluster__pb2.LPopRequest.SerializeToString,
            rustycluster__pb2.LPopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RPop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/RPop',
            rustycluster__pb2.RPopRequest.SerializeToString,
            rustycluster__pb2.RPopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/LRange',
            rustycluster__pb2.LRangeRequest.SerializeToString,
            rustycluster__pb2.LRangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LLen(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/LLen',
            rustycluster__pb2.LLenRequest.SerializeToString,
            rustycluster__pb2.LLenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LTrim(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/LTrim',
            rustycluster__pb2.LTrimRequest.SerializeToString,
            rustycluster__pb2.LTrimResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/LIndex',
            rustycluster__pb2.LIndexRequest.SerializeToString,
            rustycluster__pb2.LIndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/LSet',
            rustycluster__pb2.LSetRequest.SerializeToString,
            rustycluster__pb2.LSetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LRem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/LRem',
            rustycluster__pb2.LRemRequest.SerializeToString,
            rustycluster__pb2.LRemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LInsert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/LInsert',
            rustycluster__pb2.LInsertRequest.SerializeToString,
            rustycluster__pb2.LInsertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LPushX(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/LPushX',
            rustycluster__pb2.LPushXRequest.SerializeToString,
            rustycluster__pb2.LPushXResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RPushX(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/RPushX',
            rustycluster__pb2.RPushXRequest.SerializeToString,
            rustycluster__pb2.RPushXResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LPos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/LPos',
            rustycluster__pb2.LPosRequest.SerializeToString,
            rustycluster__pb2.LPosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def XAdd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/XAdd',
            rustycluster__pb2.XAddRequest.SerializeToString,
            rustycluster__pb2.XAddResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def XRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/XRead',
            rustycluster__pb2.XReadRequest.SerializeToString,
            rustycluster__pb2.XReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchWrite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rustycluster.KeyValueService/BatchWrite',
            rustycluster__pb2.BatchWriteRequest.SerializeToString,
            rustycluster__pb2.BatchWriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
